spring.data.mongodb.uri=mongodb://localhost:27017/Finance
spring.data.mongodb.database=Finance

jwt.secret=7d428bfaf20bb3cf3383f9abfdb4a5b4c108183141f2a08892dc479bde67a35c
app.encryption.secret-key=dGhpcy1pcy1hLTMyLWNoYXItc2VjcmV0
totp.encryption-key=1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef

brevo.api-key=dummy-brevo-key

zerodha.redirect.url=http://localhost:3000/brokers/zerodha/callback
frontend.url=http://localhost:3000
app.cors.allowed-origins=http://localhost:3000
